spring:
  application:
    name: backend

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=subastas_db;encrypt=true;trustServerCertificate=true
    username: userSubastas
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

server:
  port: 8080